### ISSUE TITLE
Add `Framework :: Hypothesis` PyPI trove classifier

### ISSUE THREAD

**Issue by Zac-HD** [stratis-storage/hs-dbus-signature#17]
The Python Packaging Authority has recently created a new trove classifier to help users find Hypothesis-related packages, as described and demonstrated in HypothesisWorks/hypothesis#1663.

It would be great if this package used it too!

(it would also be good to set up a link from the PyPI page back to this repo)

**Comment by mulkieran** [comment]
Sure! And thanks for getting the classifier set up.

**Comment by Zac-HD** [comment]
Closes by #17 :heart_eyes:
